### ISSUE TITLE
Overflow error in graph

### ISSUE THREAD

**Issue by app-git-hub** [soniakeys/graph#41]
Hi Sonia,

I am getting:
```
C:\Projects\Go\gd\gdrive>go build
# github.com/soniakeys/graph
..\..\src\github.com\soniakeys\graph\bits.go:71: constant 285870213051353865 ove
rflows big.Word
```

I am on windows 32-bit, can you help fix that for windows users?

**Comment by soniakeys** [comment]
Yep.  It's hard coded to 64 bits currently out of sheer laziness.  I'll try to verify the (expected) error with a 32-bit build, add a 32-bit build to travis, then add the fix.  Shouldn't take long, lemme fix some coffee first.

**Comment by soniakeys** [comment]
Fixed.  Thank you for filing this!  Please reopen if it's still not working for you.

**Comment by soniakeys** [comment]
Err, there was a bug...but it should be fixed now.

**Comment by willemw12** [comment]
Still an issue on "linux_arm":

    $ go get github.com/prasmussen/gdrive
    # github.com/soniakeys/graph
    ../go/src/github.com/soniakeys/graph/bits64.go:56: constant 285870213051353865 overflows big.Word

**Comment by soniakeys** [comment]
I pushed a change to recognize arm but I have no way of testing it.  If you (or anyone) can confirm it working on arm that would be wonderful.

**Comment by willemw12** [comment]
It's working now on "linux_arm".

**Comment by soniakeys** [comment]
awesome.  thank you!
